apiVersion: v1
kind: Namespace
metadata:
  name: projectnowcdp-report-studio-dev
  labels:
    app.kubernetes.io/name: projectnowcdp-report-studio
    app.kubernetes.io/part-of: projectnowcdp
    environment: dev
    team: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: projectnowcdp-report-studio-staging
  labels:
    app.kubernetes.io/name: projectnowcdp-report-studio
    app.kubernetes.io/part-of: projectnowcdp
    environment: staging
    team: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: projectnowcdp-report-studio-production
  labels:
    app.kubernetes.io/name: projectnowcdp-report-studio
    app.kubernetes.io/part-of: projectnowcdp
    environment: production
    team: frontend
