apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectnowcdp-report-studio
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: projectnowcdp-report-studio
      containers:
        - name: projectnowcdp-report-studio
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projectnowcdp-report-studio
spec:
  tls:
    - hosts:
        - "*.report.projectnowcdp.com"
      secretName: projectnowcdp-report-studio-production-tls
  rules:
    - host: "*.report.projectnowcdp.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: projectnowcdp-report-studio
                port:
                  number: 80
