apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: projectnowcdp-report-studio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: projectnowcdp-report-studio
