<template>
    <div class="table-element-container">
        <BaseElement
            :element="element"
            :band-index="bandIndex"
            :element-index="elementIndex"
            :selected-element="selectedElement"
            :selected-elements="selectedElements"
            :is-dragging="isDragging"
            :is-out-of-bounds="isOutOfBounds"
            :parent-frame-index="parentFrameIndex"
            @select="handleSelect"
            @drag-start="handleDragStart"
            @resize-start="handleResizeStart"
            @contextmenu="handleContextMenu"
        >
            <!-- Table content -->
            <div class="table-content">
                <table class="designer-table">
                    <!-- Table header region -->
                    <thead>
                        <!-- Table header -->
                        <template
                            v-if="hasTableHeader && tableHeaderHeight > 0"
                        >
                            <template v-if="hasTableHeaderGroups">
                                <!-- Render the rows generated by the group directly, without adding an outer tr -->
                                <render-column-group
                                    :group="rootGroup"
                                    :level="0"
                                    :type="'tableHeader'"
                                    :report-styles="reportStyles"
                                    :table-styles="tableStyles"
                                    @column-click="handleRenderColumnClick"
                                    @row-resize-start="handleRowResizeStart"
                                />
                            </template>
                            <template v-else>
                                <!-- Header for regular columns -->
                                <tr
                                    class="tableHeader"
                                    :style="{
                                        height: `${tableHeaderHeight}px`,
                                        ...getRowStyle('tableHeader'),
                                    }"
                                    @mousedown="
                                        handleNonGroupedRowMouseDown(
                                            $event,
                                            'tableHeader',
                                        )
                                    "
                                >
                                    <n-tooltip
                                        v-for="(column, index) in columns"
                                        :key="column.uuid"
                                        placement="top"
                                        trigger="hover"
                                    >
                                        <template #trigger>
                                            <th
                                                :style="{
                                                    width: `${column.width}px`,
                                                }"
                                                class="table-column table-header-cell"
                                                :class="{
                                                    'column-selected':
                                                        isColumnSelected(index),
                                                }"
                                                @click.stop="
                                                    handleColumnClick(
                                                        index,
                                                        $event,
                                                    )
                                                "
                                            >
                                                <!-- Buttons to adjust column order -->
                                                <!-- Move left button -->
                                                <n-button
                                                    v-if="index > 0"
                                                    class="order-button left-button"
                                                    @click="
                                                        moveColumn(
                                                            index,
                                                            'left',
                                                        )
                                                    "
                                                    :title="
                                                        t(
                                                            'properties.moveColumnLeft',
                                                        )
                                                    "
                                                    type="default"
                                                    quaternary
                                                    circle
                                                    size="small"
                                                >
                                                    ◀
                                                </n-button>

                                                <!-- Move right button -->
                                                <n-button
                                                    v-if="
                                                        index <
                                                        columns.length - 1
                                                    "
                                                    class="order-button right-button"
                                                    @click="
                                                        moveColumn(
                                                            index,
                                                            'right',
                                                        )
                                                    "
                                                    :title="
                                                        t(
                                                            'properties.moveColumnRight',
                                                        )
                                                    "
                                                    type="default"
                                                    quaternary
                                                    circle
                                                    size="small"
                                                >
                                                    ▶
                                                </n-button>

                                                <div
                                                    v-if="
                                                        column.hasTableHeader &&
                                                        column.tableHeader
                                                    "
                                                    class="cell-content"
                                                    :style="
                                                        getCellStyle(
                                                            column.tableHeader,
                                                            'tableHeader',
                                                        )
                                                    "
                                                >
                                                    <!-- Render header content -->
                                                    <template
                                                        v-if="
                                                            column.tableHeader
                                                                .element
                                                                ?.type ===
                                                            'staticText'
                                                        "
                                                    >
                                                        <div
                                                            class="static-text"
                                                        >
                                                            {{
                                                                column
                                                                    .tableHeader
                                                                    .element
                                                                    ?.text
                                                            }}
                                                        </div>
                                                    </template>
                                                    <template
                                                        v-else-if="
                                                            column.tableHeader
                                                                .element
                                                                ?.type ===
                                                            'textField'
                                                        "
                                                    >
                                                        <div class="text-field">
                                                            {{
                                                                column
                                                                    .tableHeader
                                                                    .element
                                                                    ?.expression
                                                            }}
                                                        </div>
                                                    </template>
                                                </div>
                                                <div
                                                    v-else-if="
                                                        column.hasTableHeader
                                                    "
                                                    class="cell-content empty"
                                                ></div>
                                                <div
                                                    v-else
                                                    class="cell-content empty"
                                                ></div>
                                                <!-- Column width drag handle -->
                                                <div
                                                    v-if="
                                                        index <
                                                        columns.length - 1
                                                    "
                                                    class="column-resize-handle"
                                                    @mousedown.stop.prevent="
                                                        startColumnResize(
                                                            index,
                                                            $event,
                                                        )
                                                    "
                                                ></div>
                                            </th>
                                        </template>
                                        <template #default>
                                            Width: {{ column.width }}px
                                        </template>
                                    </n-tooltip>
                                </tr>
                            </template>
                        </template>
                        <!-- Column header -->
                        <template v-if="columnHeaderHeight > 0">
                            <template v-if="hasColumnHeaderGroups">
                                <!-- Render the rows generated by the group directly, without adding an outer tr -->
                                <render-column-group
                                    :group="rootGroup"
                                    :level="0"
                                    :type="'columnHeader'"
                                    :report-styles="reportStyles"
                                    :table-styles="tableStyles"
                                    @column-click="handleRenderColumnClick"
                                    @row-resize-start="handleRowResizeStart"
                                />
                            </template>
                            <template v-else>
                                <!-- Header for regular columns -->
                                <tr
                                    class="columnHeader"
                                    :style="{
                                        height: `${columnHeaderHeight}px`,
                                        ...getRowStyle('columnHeader'),
                                    }"
                                    @mousedown="
                                        handleNonGroupedRowMouseDown(
                                            $event,
                                            'columnHeader',
                                        )
                                    "
                                >
                                    <n-tooltip
                                        v-for="(column, index) in columns"
                                        :key="column.uuid"
                                        placement="top"
                                        trigger="hover"
                                    >
                                        <template #trigger>
                                            <th
                                                :style="{
                                                    width: `${column.width}px`,
                                                }"
                                                class="table-column column-header-cell"
                                                :class="{
                                                    'column-selected':
                                                        isColumnSelected(index),
                                                }"
                                                @click.stop="
                                                    handleColumnClick(
                                                        index,
                                                        $event,
                                                    )
                                                "
                                                @dblclick.stop="
                                                    startCellEditing(
                                                        index,
                                                        'columnHeader',
                                                    )
                                                "
                                            >
                                                <div
                                                    v-if="
                                                        editingCell &&
                                                        editingCell.columnIndex ===
                                                            index &&
                                                        editingCell.cellType ===
                                                            'columnHeader'
                                                    "
                                                    class="cell-edit-input"
                                                >
                                                    <input
                                                        ref="cellEditInput"
                                                        :value="
                                                            column.columnHeader
                                                                ?.element
                                                                ?.type ===
                                                            'staticText'
                                                                ? column
                                                                      .columnHeader
                                                                      .element
                                                                      .text
                                                                : column
                                                                        .columnHeader
                                                                        ?.element
                                                                        ?.type ===
                                                                    'textField'
                                                                  ? column
                                                                        .columnHeader
                                                                        .element
                                                                        .expression
                                                                  : ''
                                                        "
                                                        @input="
                                                            updateCellEditingValue(
                                                                $event,
                                                            )
                                                        "
                                                        @blur="
                                                            finishCellEditing
                                                        "
                                                        @keydown.enter="
                                                            finishCellEditing
                                                        "
                                                        @keydown.escape="
                                                            cancelCellEditing
                                                        "
                                                        class="inline-edit-input"
                                                    />
                                                </div>
                                                <div
                                                    v-else
                                                    class="cell-content"
                                                    :style="
                                                        getColumnHeaderStyle(
                                                            column,
                                                        )
                                                    "
                                                >
                                                    <!-- Render column header content, taking the actual static text or dynamic text expression from columnHeader -->
                                                    <template
                                                        v-if="
                                                            column.columnHeader
                                                        "
                                                    >
                                                        <template
                                                            v-if="
                                                                column
                                                                    .columnHeader
                                                                    .element
                                                                    ?.type ===
                                                                'staticText'
                                                            "
                                                        >
                                                            <div
                                                                class="static-text"
                                                            >
                                                                {{
                                                                    column
                                                                        .columnHeader
                                                                        .element
                                                                        ?.text ||
                                                                    ""
                                                                }}
                                                            </div>
                                                        </template>
                                                        <template
                                                            v-else-if="
                                                                column
                                                                    .columnHeader
                                                                    .element
                                                                    ?.type ===
                                                                'textField'
                                                            "
                                                        >
                                                            <div
                                                                class="text-field"
                                                            >
                                                                {{
                                                                    column
                                                                        .columnHeader
                                                                        .element
                                                                        ?.expression ||
                                                                    ""
                                                                }}
                                                            </div>
                                                        </template>
                                                        <template v-else>
                                                            <div
                                                                class="column-name"
                                                            >
                                                                {{
                                                                    column.name
                                                                }}
                                                            </div>
                                                        </template>
                                                    </template>
                                                    <template v-else>
                                                        <div
                                                            class="column-name"
                                                        >
                                                            {{ column.name }}
                                                        </div>
                                                    </template>
                                                </div>
                                                <!-- Column width drag handle -->
                                                <div
                                                    v-if="
                                                        index <
                                                        columns.length - 1
                                                    "
                                                    class="column-resize-handle"
                                                    @mousedown.stop.prevent="
                                                        startColumnResize(
                                                            index,
                                                            $event,
                                                        )
                                                    "
                                                ></div>
                                            </th>
                                        </template>
                                        <template #default>
                                            Width: {{ column.width }}px
                                        </template>
                                    </n-tooltip>
                                </tr>
                            </template>
                        </template>
                    </thead>
                    <!-- Table body region -->
                    <tbody>
                        <!-- Detail row -->
                        <tr
                            v-if="detailCellHeight > 0"
                            class="cellDetail"
                            :style="{
                                height: `${detailCellHeight}px`,
                                ...getRowStyle('detailCell'),
                            }"
                        >
                            <n-tooltip
                                v-for="(column, index) in columns"
                                :key="column.uuid"
                                placement="top"
                                trigger="hover"
                            >
                                <template #trigger>
                                    <td
                                        :style="{ width: `${column.width}px` }"
                                        class="table-column detail-cell"
                                        :class="{
                                            'column-selected':
                                                isColumnSelected(index),
                                        }"
                                        @click.stop="
                                            handleColumnClick(index, $event)
                                        "
                                        @dblclick.stop="
                                            startCellEditing(
                                                index,
                                                'detailCell',
                                            )
                                        "
                                    >
                                        <div
                                            v-if="
                                                editingCell &&
                                                editingCell.columnIndex ===
                                                    index &&
                                                editingCell.cellType ===
                                                    'detailCell'
                                            "
                                            class="cell-edit-input"
                                        >
                                            <input
                                                ref="cellEditInput"
                                                :value="
                                                    column.detailCell?.element
                                                        ?.type === 'staticText'
                                                        ? column.detailCell
                                                              .element.text
                                                        : column.detailCell
                                                                ?.element
                                                                ?.type ===
                                                            'textField'
                                                          ? column.detailCell
                                                                .element
                                                                .expression
                                                          : ''
                                                "
                                                @input="
                                                    updateCellEditingValue(
                                                        $event,
                                                    )
                                                "
                                                @blur="finishCellEditing"
                                                @keydown.enter="
                                                    finishCellEditing
                                                "
                                                @keydown.escape="
                                                    cancelCellEditing
                                                "
                                                class="inline-edit-input"
                                            />
                                        </div>
                                        <div
                                            v-else-if="column.detailCell"
                                            class="cell-content"
                                            :style="
                                                getCellStyle(
                                                    column.detailCell,
                                                    'detailCell',
                                                )
                                            "
                                        >
                                            <!-- Render detail content -->
                                            <template
                                                v-if="column.detailCell.element"
                                            >
                                                <template
                                                    v-if="
                                                        column.detailCell
                                                            .element.type ===
                                                        'staticText'
                                                    "
                                                >
                                                    <div class="static-text">
                                                        {{
                                                            column.detailCell
                                                                .element.text
                                                        }}
                                                    </div>
                                                </template>
                                                <template
                                                    v-else-if="
                                                        column.detailCell
                                                            .element.type ===
                                                        'textField'
                                                    "
                                                >
                                                    <div class="text-field">
                                                        {{
                                                            column.detailCell
                                                                .element
                                                                .expression
                                                        }}
                                                    </div>
                                                </template>
                                            </template>
                                        </div>
                                        <div
                                            v-else
                                            class="cell-content empty"
                                        ></div>
                                    </td>
                                </template>
                                <template #default>
                                    Width: {{ column.width }}px
                                </template>
                            </n-tooltip>
                        </tr>
                    </tbody>
                    <!-- Table footer region -->
                    <tfoot>
                        <!-- Column footer -->
                        <tr
                            v-if="columnFooterHeight > 0"
                            class="columnFooter"
                            :style="{
                                height: `${columnFooterHeight}px`,
                                ...getRowStyle('columnFooter'),
                            }"
                        >
                            <n-tooltip
                                v-for="(column, index) in columns"
                                :key="column.uuid"
                                placement="top"
                                trigger="hover"
                            >
                                <template #trigger>
                                    <td
                                        :style="{ width: `${column.width}px` }"
                                        class="table-column column-footer-cell"
                                        :class="{
                                            'column-selected':
                                                isColumnSelected(index),
                                        }"
                                        @click.stop="
                                            handleColumnClick(index, $event)
                                        "
                                    >
                                        <div
                                            v-if="column.columnFooter"
                                            class="cell-content"
                                            :style="
                                                getCellStyle(
                                                    column.columnFooter,
                                                    'columnFooter',
                                                )
                                            "
                                        >
                                            <!-- Render column footer content -->
                                            <template
                                                v-if="
                                                    column.columnFooter.element
                                                "
                                            >
                                                <template
                                                    v-if="
                                                        column.columnFooter
                                                            .element.type ===
                                                        'staticText'
                                                    "
                                                >
                                                    <div class="static-text">
                                                        {{
                                                            (
                                                                column
                                                                    .columnFooter
                                                                    .element as StaticTextElement
                                                            ).text || ""
                                                        }}
                                                    </div>
                                                </template>
                                                <template
                                                    v-else-if="
                                                        column.columnFooter
                                                            .element.type ===
                                                        'textField'
                                                    "
                                                >
                                                    <div class="text-field">
                                                        {{
                                                            (
                                                                column
                                                                    .columnFooter
                                                                    .element as TextFieldElement
                                                            ).expression || ""
                                                        }}
                                                    </div>
                                                </template>
                                            </template>
                                        </div>
                                        <div
                                            v-else
                                            class="cell-content empty"
                                        ></div>
                                    </td>
                                </template>
                                <template #default>
                                    Width: {{ column.width }}px
                                </template>
                            </n-tooltip>
                        </tr>
                        <!-- Table footer -->
                        <tr
                            v-if="tableFooterHeight > 0"
                            class="tableFooter"
                            :style="{
                                height: `${tableFooterHeight}px`,
                                ...getRowStyle('tableFooter'),
                            }"
                        >
                            <n-tooltip
                                v-for="(column, index) in columns"
                                :key="column.uuid"
                                placement="top"
                                trigger="hover"
                            >
                                <template #trigger>
                                    <td
                                        :style="{ width: `${column.width}px` }"
                                        class="table-column detail-cell"
                                        :class="{
                                            'column-selected':
                                                isColumnSelected(index),
                                        }"
                                        @click.stop="
                                            handleColumnClick(index, $event)
                                        "
                                    >
                                        <div
                                            v-if="column.tableFooter"
                                            class="cell-content"
                                            :style="
                                                getCellStyle(
                                                    column.tableFooter,
                                                    'tableFooter',
                                                )
                                            "
                                        >
                                            <!-- Render table footer content -->
                                            <template
                                                v-if="
                                                    column.tableFooter.element
                                                "
                                            >
                                                <template
                                                    v-if="
                                                        column.tableFooter
                                                            .element.type ===
                                                        'staticText'
                                                    "
                                                >
                                                    <div class="static-text">
                                                        {{
                                                            (
                                                                column
                                                                    .tableFooter
                                                                    .element as StaticTextElement
                                                            ).text || ""
                                                        }}
                                                    </div>
                                                </template>
                                                <template
                                                    v-else-if="
                                                        column.tableFooter
                                                            .element.type ===
                                                        'textField'
                                                    "
                                                >
                                                    <div class="text-field">
                                                        {{
                                                            (
                                                                column
                                                                    .tableFooter
                                                                    .element as TextFieldElement
                                                            ).expression || ""
                                                        }}
                                                    </div>
                                                </template>
                                            </template>
                                        </div>
                                        <div
                                            v-else
                                            class="cell-content empty"
                                        ></div>
                                    </td>
                                </template>
                                <template #default>
                                    Width: {{ column.width }}px
                                </template>
                            </n-tooltip>
                        </tr>
                    </tfoot>
                </table>
            </div>

            <!-- Selection border -->
            <SelectionBox
                v-if="isSelected"
                :element="element"
                :is-resizing="isResizing"
                :on-resize="handleResize"
                :on-resize-start="handleResizeStart"
                :on-resize-end="handleResizeEnd"
            />
        </BaseElement>
    </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, nextTick } from "vue";
import { NButton, NTooltip } from "naive-ui";
import { useI18n } from "vue-i18n";
import BaseElement from "./BaseElement.vue";
import SelectionBox from "../designer/SelectionBox.vue";
import RenderColumnGroup from "./RenderColumnGroup.vue";

const { t } = useI18n();
import type {
    DesignElement,
    SelectedElementInfo,
    EditingElementInfo,
    TableElement as TableElementType,
    StaticTextElement,
    TextFieldElement,
} from "../../types";

const props = defineProps<{
    element: DesignElement;
    bandIndex: number;
    elementIndex: number;
    selectedElement: SelectedElementInfo | null;
    selectedElements: Array<{
        bandIndex: number;
        elementIndex: number;
        parentFrameIndex?: number;
    }>;
    editingElement: EditingElementInfo | null;
    isDragging?: boolean;
    isOutOfBounds?: boolean;
    parentFrameIndex?: number;
    zoomLevel?: number;
    reportStyles?: any[];
    tableStyles?: {
        tableHeader: string;
        columnHeader: string;
        columnFooter: string;
        detailCell: string;
    };
}>();

const emit = defineEmits<{
    select: [
        bandIndex: number,
        elementIndex: number,
        isMultiSelect: boolean,
        parentFrameIndex?: number,
    ];
    dragStart: [
        event: MouseEvent,
        bandIndex: number,
        elementIndex: number,
        parentFrameIndex?: number,
    ];
    resizeStart: [
        event: MouseEvent,
        bandIndex: number,
        elementIndex: number,
        parentFrameIndex?: number,
    ];
    resizeEnd: [];
    contextmenu: [
        event: MouseEvent,
        bandIndex: number,
        elementIndex: number,
        parentFrameIndex?: number,
    ];
    moveColumn: [elementIndex: number, fromIndex: number, toIndex: number];
    "update-jrxml": [];
}>();

// Move column left or right
function moveColumn(index: number, direction: "left" | "right") {
    const newIndex = direction === "left" ? index - 1 : index + 1;
    if (newIndex < 0 || newIndex >= columns.value.length) return;

    // Emit move column event to parent component
    emit("moveColumn", props.elementIndex, index, newIndex);
}

const isResizing = ref(false);
const tableElement = computed(() => props.element as TableElementType);
const columns = computed(() => tableElement.value.columns || []);

// Collect all columns (including columns inside groups), used for height calculation
const allColumnsForHeight = computed(() => {
    const result: any[] = [];

    // Function to recursively extract all columns
    function extractColumns(items: any[]) {
        if (!items) return;
        items.forEach((item: any) => {
            if ('detailCell' in item) {
                // It's a regular column (TableColumn)
                result.push(item);
            } else if ('children' in item && item.children) {
                // It's a group (ColumnGroup), recursively extract child columns
                extractColumns(item.children);
            }
        });
    }

    // Collect regular columns from the columns array
    if (tableElement.value.columns) {
        result.push(...tableElement.value.columns);
    }
    // Recursively collect all columns from the children array (including columns in nested groups)
    if (tableElement.value.children) {
        extractColumns(tableElement.value.children);
    }
    return result;
});

// Column selection state management
const selectedColumns = ref<number[]>([]);

// ========== Column width dragging ==========
const columnResizeState = ref<{
    columnIndex: number;
    startX: number;
    originalWidthLeft: number;
    originalWidthRight: number;
} | null>(null);

function startColumnResize(columnIndex: number, event: MouseEvent) {
    const leftCol = columns.value[columnIndex];
    const rightCol = columns.value[columnIndex + 1];
    if (!leftCol || !rightCol) return;

    columnResizeState.value = {
        columnIndex,
        startX: event.clientX,
        originalWidthLeft: leftCol.width,
        originalWidthRight: rightCol.width,
    };

    document.addEventListener("mousemove", handleColumnResizeMove);
    document.addEventListener("mouseup", handleColumnResizeEnd);
    document.body.style.cursor = "col-resize";
    document.body.style.userSelect = "none";
}

function handleColumnResizeMove(e: MouseEvent) {
    const state = columnResizeState.value;
    if (!state) return;

    const delta = e.clientX - state.startX;
    const leftCol = columns.value[state.columnIndex];
    const rightCol = columns.value[state.columnIndex + 1];
    if (!leftCol || !rightCol) return;

    const minW = 30;
    let newLeft = state.originalWidthLeft + delta;
    let newRight = state.originalWidthRight - delta;

    if (newLeft < minW) {
        newLeft = minW;
        newRight = state.originalWidthLeft + state.originalWidthRight - minW;
    }
    if (newRight < minW) {
        newRight = minW;
        newLeft = state.originalWidthLeft + state.originalWidthRight - minW;
    }

    leftCol.width = Math.round(newLeft);
    rightCol.width = Math.round(newRight);

    // Sync-update the corresponding column's width in element.children
    updateChildrenColumnWidth(leftCol.uuid, leftCol.width);
    updateChildrenColumnWidth(rightCol.uuid, rightCol.width);

    // Recalculate the table's total width
    const total = columns.value.reduce((sum, c) => sum + c.width, 0);
    tableElement.value.width = total;
}

function handleColumnResizeEnd() {
    columnResizeState.value = null;
    document.removeEventListener("mousemove", handleColumnResizeMove);
    document.removeEventListener("mouseup", handleColumnResizeEnd);
    document.body.style.cursor = "";
    document.body.style.userSelect = "";
    emit("update-jrxml");
}

// Recursively find and update the column width in the children tree
function updateChildrenColumnWidth(uuid: string, width: number) {
    const children = tableElement.value.children;
    if (!children) return;
    for (const child of children) {
        if ((child as any).uuid === uuid) {
            (child as any).width = width;
            // Sync-update the cell width
            const cells = [
                (child as any).tableHeader,
                (child as any).columnHeader,
                (child as any).detailCell,
                (child as any).columnFooter,
                (child as any).tableFooter,
            ];
            cells.forEach((cell: any) => {
                if (cell?.element) cell.element.width = width;
            });
        }
        if ((child as any).children) {
            updateChildrenColumnWidthInGroup(
                (child as any).children,
                uuid,
                width,
            );
        }
    }
}

function updateChildrenColumnWidthInGroup(
    children: any[],
    uuid: string,
    width: number,
) {
    for (const child of children) {
        if (child.uuid === uuid) {
            child.width = width;
            const cells = [
                child.tableHeader,
                child.columnHeader,
                child.detailCell,
                child.columnFooter,
                child.tableFooter,
            ];
            cells.forEach((cell: any) => {
                if (cell?.element) cell.element.width = width;
            });
        }
        if (child.children) {
            updateChildrenColumnWidthInGroup(child.children, uuid, width);
        }
    }
}

// ========== Inline cell editing ==========
const editingCell = ref<{ columnIndex: number; cellType: string } | null>(null);
const cellEditInput = ref<HTMLInputElement | null>(null);
const cellEditValue = ref("");

function startCellEditing(columnIndex: number, cellType: string) {
    const column = columns.value[columnIndex];
    if (!column) return;

    let cell: any;
    if (cellType === "columnHeader") cell = column.columnHeader;
    else if (cellType === "detailCell") cell = column.detailCell;
    else return;

    const elem = cell?.element;
    if (!elem) return;

    editingCell.value = { columnIndex, cellType };
    cellEditValue.value =
        elem.type === "staticText" ? elem.text || "" : elem.expression || "";

    nextTick(() => {
        if (cellEditInput.value) {
            cellEditInput.value.focus();
            cellEditInput.value.select();
        }
    });
}

function updateCellEditingValue(event: Event) {
    cellEditValue.value = (event.target as HTMLInputElement).value;
}

function finishCellEditing() {
    if (!editingCell.value) return;

    const column = columns.value[editingCell.value.columnIndex];
    if (!column) {
        editingCell.value = null;
        return;
    }

    let cell: any;
    if (editingCell.value.cellType === "columnHeader")
        cell = column.columnHeader;
    else if (editingCell.value.cellType === "detailCell")
        cell = column.detailCell;

    const elem = cell?.element;
    if (elem) {
        if (elem.type === "staticText") elem.text = cellEditValue.value;
        else if (elem.type === "textField")
            elem.expression = cellEditValue.value;
    }

    editingCell.value = null;
    emit("update-jrxml");
}

function cancelCellEditing() {
    editingCell.value = null;
}

// Compute whether the element is selected, using logic consistent with BaseElement
const isSelected = computed(() => {
    // 2. Fall back to index comparison (helper: treat undefined as -1 for comparison)
    const getPFI = (pfi: number | undefined) => (pfi === undefined ? -1 : pfi);
    const currentPFI = getPFI(props.parentFrameIndex);

    // Check whether it's in the multi-select list
    if (props.selectedElements && props.selectedElements.length > 0) {
        return props.selectedElements.some(
            (el) =>
                el.bandIndex === props.bandIndex &&
                el.elementIndex === props.elementIndex &&
                getPFI(el.parentFrameIndex) === currentPFI,
        );
    }

    // Single select logic
    return (
        props.selectedElement &&
        props.selectedElement.bandIndex === props.bandIndex &&
        props.selectedElement.elementIndex === props.elementIndex &&
        getPFI(props.selectedElement.parentFrameIndex) === currentPFI
    );
});

// Determine whether a column is selected
function isColumnSelected(index: number): boolean {
    return selectedColumns.value.includes(index);
}

// Handle the select event
const handleSelect = (
    bandIndex: number,
    elementIndex: number,
    isMultiSelect?: boolean,
    parentFrameIndex?: number,
) => {
    emit(
        "select",
        bandIndex,
        elementIndex,
        isMultiSelect || false,
        parentFrameIndex,
    );
};

// Handle the RenderColumnGroup component's click event
const handleRenderColumnClick = (column: any, event: MouseEvent) => {
    // Directly emit the table element's select event
    emit(
        "select",
        props.bandIndex,
        props.elementIndex,
        false,
        props.parentFrameIndex,
    );
};

// Handle row height drag resize
// Handle mousedown on non-grouped table rows (row height dragging)
function handleNonGroupedRowMouseDown(event: MouseEvent, type: string) {
    // Only trigger row-height dragging when clicking the ::after pseudo-element (i.e. the tr itself);
    // clicking th/td children is handled by element dragging and doesn't conflict
    if (event.target !== event.currentTarget) return;

    const tr = event.currentTarget as HTMLElement;
    const rect = tr.getBoundingClientRect();
    const distanceFromBottom = rect.bottom - event.clientY;

    if (distanceFromBottom <= 6) {
        const height = getMaxCellHeight(
            (col: any) => (col as any)[type],
        );
        handleRowResizeStart({
            rowIndex: 0,
            startY: event.clientY,
            originalHeight: height,
            type: type,
            rows: [],
        });
        event.preventDefault();
        event.stopPropagation();
    }
}

function handleRowResizeStart(info: {
    rowIndex: number;
    startY: number;
    originalHeight: number;
    type: string;
    rows: any[][];
}) {
    const { startY, originalHeight, type, rows } = info;

    const onMouseMove = (e: MouseEvent) => {
        const delta = e.clientY - startY;
        const newHeight = Math.max(10, Math.round(originalHeight + delta));

        // Update the height of all cells in this row
        for (const row of rows) {
            const firstCell = row[0];
            if (!firstCell) continue;
            const cellContent = firstCell.content;
            if (cellContent && cellContent[type]) {
                const currentH = cellContent[type].height || 30;
                const rs = cellContent[type].rowSpan || 1;
                if (rs <= 1) {
                    // Non-merged cell, update directly
                    cellContent[type].height = newHeight;
                    if (cellContent[type].element) {
                        cellContent[type].element.height = newHeight;
                    }
                } else {
                    // Merged cell, update by row height * row span
                    cellContent[type].height = newHeight * rs;
                    if (cellContent[type].element) {
                        cellContent[type].element.height = newHeight * rs;
                    }
                }
            }
        }

        // Sync-update the cell heights in the columns array
        for (const col of columns.value) {
            const cell = (col as any)[type];
            if (cell) {
                const rs = cell.rowSpan || 1;
                if (rs <= 1) {
                    cell.height = newHeight;
                    if (cell.element) cell.element.height = newHeight;
                } else {
                    cell.height = newHeight * rs;
                    if (cell.element) cell.element.height = newHeight * rs;
                }
            }
        }

        // Sync-update the cell heights in the children tree (children may be a different reference from columns after syncTableColumns)
        if (tableElement.value.children) {
            for (const child of tableElement.value.children) {
                syncChildCellHeight(child, type, newHeight);
            }
        }
    };

    const onMouseUp = () => {
        document.removeEventListener("mousemove", onMouseMove);
        document.removeEventListener("mouseup", onMouseUp);
        document.body.style.cursor = "";
        document.body.style.userSelect = "";
        emit("update-jrxml");
    };

    document.addEventListener("mousemove", onMouseMove);
    document.addEventListener("mouseup", onMouseUp);
    document.body.style.cursor = "ns-resize";
    document.body.style.userSelect = "none";
}

// Recursively sync the cell heights in the children tree
function syncChildCellHeight(child: any, type: string, newHeight: number) {
    if (child.children) {
        // Column group, recursively process child nodes
        for (const sub of child.children) {
            syncChildCellHeight(sub, type, newHeight);
        }
    }
    const cell = (child as any)[type];
    if (cell) {
        const rs = cell.rowSpan || 1;
        if (rs <= 1) {
            cell.height = newHeight;
            if (cell.element) cell.element.height = newHeight;
        } else {
            cell.height = newHeight * rs;
            if (cell.element) cell.element.height = newHeight * rs;
        }
    }
}

// Handle the drag start event
const handleDragStart = (
    event: MouseEvent,
    bandIndex: number,
    elementIndex: number,
    parentFrameIndex?: number,
) => {
    emit("dragStart", event, bandIndex, elementIndex, parentFrameIndex);
};

// Handle the context menu event
const handleContextMenu = (
    event: MouseEvent,
    bandIndex: number,
    elementIndex: number,
    parentFrameIndex?: number,
) => {
    event.preventDefault();
    event.stopPropagation();
    emit("contextmenu", event, bandIndex, elementIndex, parentFrameIndex);
};

// Resize event
const handleResize = (newWidth: number, newHeight: number) => {
    // Element size updates are needed here, handled by the parent component
};

// Resize start event
const handleResizeStart = (
    event: MouseEvent,
    bandIndex: number,
    elementIndex: number,
    parentFrameIndex?: number,
) => {
    event.stopPropagation();
    emit("resizeStart", event, bandIndex, elementIndex, parentFrameIndex);
    isResizing.value = true;
};

// Resize end event
const handleResizeEnd = () => {
    isResizing.value = false;
    emit("resizeEnd");
};

// Handle column click event, supporting multi-select
function handleColumnClick(index: number, event: MouseEvent) {
    const isMultiSelect = event.ctrlKey || event.shiftKey || event.metaKey;

    if (isMultiSelect) {
        // Multi-select mode: toggle the column's selected state
        if (selectedColumns.value.includes(index)) {
            // Deselect
            selectedColumns.value = selectedColumns.value.filter(
                (colIndex) => colIndex !== index,
            );
        } else {
            // Add to selection
            selectedColumns.value.push(index);
            // Keep the selected indices sorted
            selectedColumns.value.sort((a, b) => a - b);
        }
        // In multi-select mode, stop event propagation to preserve the column selection state
        event.stopPropagation();
    } else {
        // Single-select mode: select only the current column
        selectedColumns.value = [index];
        // In single-select mode, allow the event to bubble up, triggering table element selection
        // event.stopPropagation(); // Removed stopPropagation to let BaseElement handle selection
        // Directly emit the table element's select event
        emit(
            "select",
            props.bandIndex,
            props.elementIndex,
            false,
            props.parentFrameIndex,
        );
    }
}

// Get a style object by style name
function getStyleByName(styleName: string) {
    if (!props.reportStyles || !styleName) return null;
    return (
        props.reportStyles.find((style: any) => style.name === styleName) ||
        null
    );
}

// Convert a JRXML style to CSS style
function convertStyleToCSS(style: any) {
    if (!style) return {};

    const styles: any = {};

    // Text style
    if (style.fontSize) {
        styles.fontSize = `${style.fontSize}px`;
    }
    if (style.forecolor) {
        styles.color = style.forecolor;
    }
    if (style.isBold) {
        styles.fontWeight = "bold";
    }
    if (style.isItalic) {
        styles.fontStyle = "italic";
    }
    if (style.isUnderline) {
        styles.textDecoration = "underline";
    }
    if (style.mode === "Opaque" && style.backcolor) {
        styles.backgroundColor = style.backcolor;
    }

    // Text alignment
    if (style.textAlignment) {
        const align = style.textAlignment.toLowerCase();
        switch (align) {
            case "left":
                styles.justifyContent = "flex-start";
                break;
            case "center":
                styles.justifyContent = "center";
                break;
            case "right":
                styles.justifyContent = "flex-end";
                break;
            case "justified":
                styles.justifyContent = "space-between";
                break;
            default:
                styles.justifyContent = "center";
        }
    }
    // Vertical alignment
    if (style.verticalAlignment) {
        const align = style.verticalAlignment.toLowerCase();
        switch (align) {
            case "top":
                styles.alignItems = "flex-start";
                break;
            case "middle":
                styles.alignItems = "center";
                break;
            case "bottom":
                styles.alignItems = "flex-end";
                break;
            default:
                styles.alignItems = "center";
        }
    }

    // Border style
    let borderWidth = 0;
    let borderStyle = "solid";
    let borderColor = "#000000";

    if (style.box && style.box.pen) {
        borderWidth = style.box.pen.lineWidth || 0;
        borderStyle = style.box.pen.lineStyle || "solid";
        borderColor = style.box.pen.lineColor || "#000000";
    }

    if (borderWidth > 0) {
        styles.border = `${borderWidth}px ${borderStyle} ${borderColor}`;
    }

    return styles;
}

// Get the cell style
function getCellStyle(cell: any, cellType?: string) {
    if (!cell) return {};

    const styles: any = {};

    // First get the style from tableStyles based on cellType
    if (cellType && props.tableStyles) {
        let styleName = "";
        switch (cellType) {
            case "tableHeader":
                styleName = props.tableStyles.tableHeader;
                break;
            case "columnHeader":
                styleName = props.tableStyles.columnHeader;
                break;
            case "columnFooter":
                styleName = props.tableStyles.columnFooter;
                break;
            case "detailCell":
                styleName = props.tableStyles.detailCell;
                break;
        }

        if (styleName) {
            const style = getStyleByName(styleName);
            if (style) {
                Object.assign(styles, convertStyleToCSS(style));
            }
        }
    }

    // Then check whether cell has a style property, overriding the style from tableStyles
    if (cell.style) {
        const style = getStyleByName(cell.style);
        if (style) {
            Object.assign(styles, convertStyleToCSS(style));
        }
    }

    // Then apply the cell's own style, overriding the style from `style`
    // Text style
    if (cell.fontSize) {
        styles.fontSize = `${cell.fontSize}px`;
    } else {
        // Default font size 10, consistent with JasperReport Studio
        styles.fontSize = "10px";
    }
    if (cell.forecolor) {
        styles.color = cell.forecolor;
    }
    if (cell.isBold) {
        styles.fontWeight = "bold";
    } else {
        styles.fontWeight = "normal";
    }
    if (cell.isItalic) {
        styles.fontStyle = "italic";
    }
    if (cell.isUnderline) {
        styles.textDecoration = "underline";
    }
    if (cell.mode === "Opaque" && cell.backcolor) {
        styles.backgroundColor = cell.backcolor;
    }

    // Text alignment - since cell-content uses flex layout, justify-content needs to be set
    if (cell.textAlignment) {
        const align = cell.textAlignment.toLowerCase();
        switch (align) {
            case "left":
                styles.justifyContent = "flex-start";
                break;
            case "center":
                styles.justifyContent = "center";
                break;
            case "right":
                styles.justifyContent = "flex-end";
                break;
            case "justified":
                styles.justifyContent = "space-between";
                break;
            default:
                styles.justifyContent = "center";
        }
    }
    // Vertical alignment - since cell-content uses flex layout, align-items needs to be set
    if (cell.verticalAlignment) {
        const align = cell.verticalAlignment.toLowerCase();
        switch (align) {
            case "top":
                styles.alignItems = "flex-start";
                break;
            case "middle":
                styles.alignItems = "center";
                break;
            case "bottom":
                styles.alignItems = "flex-end";
                break;
            default:
                styles.alignItems = "center";
        }
    }

    // Finally apply cell.element's style, overriding the style from cell, to ensure the element's own style has the highest priority
    if (cell.element) {
        // Text style
        if (cell.element.fontSize) {
            styles.fontSize = `${cell.element.fontSize}px`;
        }
        if (cell.element.forecolor) {
            styles.color = cell.element.forecolor;
        }
        if (cell.element.isBold) {
            styles.fontWeight = "bold";
        } else {
            styles.fontWeight = "normal";
        }
        if (cell.element.isItalic) {
            styles.fontStyle = "italic";
        }
        if (cell.element.isUnderline) {
            styles.textDecoration = "underline";
        }
        if (cell.element.mode === "Opaque" && cell.element.backcolor) {
            styles.backgroundColor = cell.element.backcolor;
        }

        // Text alignment
        if (cell.element.textAlignment) {
            const align = cell.element.textAlignment.toLowerCase();
            switch (align) {
                case "left":
                    styles.justifyContent = "flex-start";
                    break;
                case "center":
                    styles.justifyContent = "center";
                    break;
                case "right":
                    styles.justifyContent = "flex-end";
                    break;
                case "justified":
                    styles.justifyContent = "space-between";
                    break;
                default:
                    styles.justifyContent = "center";
            }
        }
        // Vertical alignment
        if (cell.element.verticalAlignment) {
            const align = cell.element.verticalAlignment.toLowerCase();
            switch (align) {
                case "top":
                    styles.alignItems = "flex-start";
                    break;
                case "middle":
                    styles.alignItems = "center";
                    break;
                case "bottom":
                    styles.alignItems = "flex-end";
                    break;
                default:
                    styles.alignItems = "center";
            }
        }
    }

    return styles;
}

// Get the column header style
function getColumnHeaderStyle(column: any) {
    if (!column) return {};

    // If column.header has a style property, use it
    if (column.columnHeader) {
        return getCellStyle(column.columnHeader, "columnHeader");
    }

    // Otherwise get the style from tableStyles
    if (props.tableStyles && props.tableStyles.columnHeader) {
        const style = getStyleByName(props.tableStyles.columnHeader);
        if (style) {
            return convertStyleToCSS(style);
        }
    }

    // Otherwise return the default style
    return {
        backgroundColor: "#FFFFFF",
        fontWeight: "500",
        color: "#333",
    };
}

// ===== Column grouping related functionality =====

// Check whether there is column grouping (for Table Header)
const hasTableHeaderGroups = computed(() => {
    // Only render as a group when the column group actually defines tableHeader
    const hasGroups =
        tableElement.value.children &&
        tableElement.value.children.length > 0 &&
        tableElement.value.children.some(
            (child) =>
                (child as any).children && (child as any).children.length > 0,
        );

    if (!hasGroups) return false;

    // Check whether any column group actually defines tableHeader
    const checkHasTableHeader = (group: any): boolean => {
        if (group.tableHeader) return true;
        if (group.children) {
            return group.children.some((child: any) => {
                if (child.children) {
                    return checkHasTableHeader(child);
                } else {
                    return child.tableHeader;
                }
            });
        }
        return false;
    };

    return tableElement.value.children!.some((child: any) => {
        if (child.children) {
            return checkHasTableHeader(child);
        }
        return child.tableHeader;
    });
});

// Check whether there is column grouping (for Column Header)
const hasColumnHeaderGroups = computed(() => {
    // Only render as a group when the column group actually defines columnHeader
    const hasGroups =
        tableElement.value.children &&
        tableElement.value.children.length > 0 &&
        tableElement.value.children.some(
            (child) =>
                (child as any).children && (child as any).children.length > 0,
        );

    if (!hasGroups) return false;

    // Check whether any column group actually defines columnHeader
    const checkHasColumnHeader = (group: any): boolean => {
        if (group.columnHeader) return true;
        if (group.children) {
            return group.children.some((child: any) => {
                if (child.children) {
                    return checkHasColumnHeader(child);
                } else {
                    return child.columnHeader;
                }
            });
        }
        return false;
    };

    return tableElement.value.children!.some((child: any) => {
        if (child.children) {
            return checkHasColumnHeader(child);
        }
        return child.columnHeader;
    });
});

// Unified column grouping check, using different logic based on context
const hasColumnGroups = computed(() => {
    // Defaults to the Table Header check; the actual context determines usage
    return hasTableHeaderGroups.value;
});

// Create a virtual root group containing all children
const rootGroup = computed(() => {
    return {
        children: tableElement.value.children || [],
    };
});

// Check whether there is a table header
const hasTableHeader = computed(() => {
    if (hasColumnGroups.value) {
        // Recursively check whether any group or column has tableHeader
        const checkHasTableHeader = (group: any): boolean => {
            // First check whether the current group has tableHeader
            if (group.hasTableHeader) return true;

            // Then check the child nodes
            if (group.children) {
                return group.children.some((child: any) => {
                    if (child.children) {
                        return checkHasTableHeader(child);
                    } else {
                        return child.hasTableHeader;
                    }
                });
            }
            return false;
        };
        return checkHasTableHeader(rootGroup.value);
    } else {
        return columns.value.some((column) => column.hasTableHeader);
    }
});

// Compute the row height - take the maximum across all columns
function getMaxCellHeight(getCell: (col: any) => any): number {
    // Use allColumnsForHeight to get all columns (including columns inside groups)
    const cols = allColumnsForHeight.value;
    if (cols.length === 0) return 30;
    let maxH = 0;
    for (const col of cols) {
        const cell = getCell(col);
        const h = cell?.element?.height;
        if (h && h > maxH) maxH = h;
    }
    return maxH || 30;
}

const tableHeaderHeight = computed(() =>
    getMaxCellHeight((col) => col.tableHeader),
);
const columnHeaderHeight = computed(() =>
    getMaxCellHeight((col) => col.columnHeader),
);
const detailCellHeight = computed(() =>
    getMaxCellHeight((col) => col.detailCell),
);
const columnFooterHeight = computed(() =>
    getMaxCellHeight((col) => col.columnFooter),
);
const tableFooterHeight = computed(() =>
    getMaxCellHeight((col) => col.tableFooter),
);

// Get the column index by column UUID
function getColumnIndex(column: any): number {
    return columns.value.findIndex((col) => col.uuid === column.uuid);
}

// Get the group cell style
function getGroupCellStyle(group: any, type: string) {
    if (group[type]) {
        return getCellStyle(group[type], type);
    }

    // Get the style from tableStyles
    if (props.tableStyles) {
        let styleName = "";
        switch (type) {
            case "tableHeader":
                styleName = props.tableStyles.tableHeader;
                break;
            case "columnHeader":
                styleName = props.tableStyles.columnHeader;
                break;
        }

        if (styleName) {
            const style = getStyleByName(styleName);
            if (style) {
                return convertStyleToCSS(style);
            }
        }
    }

    // Default style
    return {
        backgroundColor: type === "tableHeader" ? "#FFFFFF" : "#FFFFFF",
        fontWeight: "600",
        color: "#333",
    };
}

// Get the cell content style
function getCellContentStyle(column: any, type: string) {
    if (column[type]) {
        return getCellStyle(column[type], type);
    }

    // Get the style from tableStyles
    if (props.tableStyles) {
        let styleName = "";
        switch (type) {
            case "tableHeader":
                styleName = props.tableStyles.tableHeader;
                break;
            case "columnHeader":
                styleName = props.tableStyles.columnHeader;
                break;
            case "columnFooter":
                styleName = props.tableStyles.columnFooter;
                break;
            case "detailCell":
                styleName = props.tableStyles.detailCell;
                break;
        }

        if (styleName) {
            const style = getStyleByName(styleName);
            if (style) {
                return convertStyleToCSS(style);
            }
        }
    }

    if (type === "columnHeader") {
        return {
            backgroundColor: "#FFFFFF",
            fontWeight: "500",
            color: "#333",
        };
    }
    return {};
}

// Get the row style
function getRowStyle(rowType: string) {
    // Get the style from tableStyles
    if (props.tableStyles) {
        let styleName = "";
        switch (rowType) {
            case "tableHeader":
                styleName = props.tableStyles.tableHeader;
                break;
            case "columnHeader":
                styleName = props.tableStyles.columnHeader;
                break;
            case "columnFooter":
                styleName = props.tableStyles.columnFooter;
                break;
            case "detailCell":
                styleName = props.tableStyles.detailCell;
                break;
            case "tableFooter":
                styleName = props.tableStyles.tableHeader;
                break;
        }

        if (styleName) {
            const style = getStyleByName(styleName);
            if (style) {
                return convertStyleToCSS(style);
            }
        }
    }
    return {};
}
</script>

<style scoped>
.table-content {
    width: 100%;
    /* Don't set height, to avoid row height being stretched due to inheritance */
    overflow: hidden;
}

.designer-table {
    width: 100%;
    /* Don't set height, to avoid row height being stretched due to inheritance by td */
    border-collapse: collapse;
    border-spacing: 0;
    table-layout: fixed; /* Fixed table layout, prevents being expanded by content */
}

/* Ensure cell content fills the entire cell without stretching the row height */
.cell-content {
    width: 100%;
    height: 100%;
    min-height: auto; /* Don't use 100% */
    display: flex;
    align-items: center; /* Vertically center */
    padding: 0 5px;
    box-sizing: border-box;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-family: inherit;
    font-size: inherit;
    font-weight: inherit;
    font-style: inherit;
    color: inherit;
    background-color: transparent;
}

.tableHeader,
.columnHeader,
.cellDetail,
.columnFooter,
.tableFooter {
    /* Don't set a default height; it's determined entirely by the height property in the JSON data */
    position: relative;
    overflow: hidden; /* Prevent content from expanding the row height */
}

/* Prevent table content from expanding the row height */
.designer-table tbody {
    vertical-align: top; /* Align table content to the top, no stretching */
}

.designer-table tr {
    vertical-align: top; /* Align row content to the top, not stretched */
}

.designer-table td {
    vertical-align: top; /* Align cell content to the top */
    height: inherit; /* Inherit the row height */
    max-height: inherit; /* Inherit the maximum height */
}

/* Row height drag handle (::after pseudo-element) */
.tableHeader::after,
.columnHeader::after,
.cellDetail::after,
.columnFooter::after,
.tableFooter::after {
    content: "";
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 6px;
    cursor: ns-resize;
    z-index: 1;
}

.tableHeader:hover::after,
.columnHeader:hover::after,
.cellDetail:hover::after,
.columnFooter:hover::after,
.tableFooter:hover::after {
    background-color: rgba(64, 158, 255, 0.2);
}

.table-column {
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    cursor: pointer;
    user-select: none;
    padding: 0;
    margin: 0;
    height: inherit; /* Inherit the row height, don't expand */
    max-height: inherit; /* Inherit the maximum height limit */
}

.table-column.th,
.table-column.td {
    padding: 0;
    margin: 0;
    height: inherit;
    max-height: inherit;
}

.designer-table th,
.designer-table td {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    overflow: hidden; /* Hide overflowing content, prevent expansion */
    height: inherit; /* Inherit the row height */
}

/* Column selected style */
.column-selected {
    background-color: rgba(64, 158, 255, 0.15);
    box-sizing: border-box;
}

.table-column:hover {
    background-color: rgba(64, 158, 255, 0.1);
}

.cell-content.empty {
    color: #999;
    font-style: italic;
}

.static-text,
.text-field,
.column-name {
    font-family: inherit;
    font-size: inherit;
    font-weight: inherit;
    font-style: inherit;
    color: inherit;
}

.text-field {
    font-family: monospace;
}

/* Column order control button style */
.table-column {
    position: relative;
    overflow: visible; /* Ensure buttons are not clipped */
}

.order-button {
    width: 7px;
    height: 7px;
    background-color: rgba(64, 158, 255, 0.85);
    color: white;
    border: none;
    border-radius: 50%;
    font-size: 6px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    box-shadow: 0 0 2px rgba(0, 0, 0, 0.15);
}

.order-button:hover {
    background-color: rgba(64, 158, 255, 1);
}

.order-button:active {
    background-color: rgba(44, 138, 235, 1);
}

/* Position buttons inside the column, on opposite sides */
.left-button {
    position: absolute;
    left: 1px;
    top: 50%;
    transform: translateY(-50%);
}

.right-button {
    position: absolute;
    right: 1px;
    top: 50%;
    transform: translateY(-50%);
}

/* Ensure the buttons are not clipped by parent elements */
.design-element {
    overflow: visible !important;
}

.table-content {
    overflow: hidden;
}

/* Table element container style */
.table-element-container {
    position: relative;
}

/* Column width drag handle */
.column-resize-handle {
    position: absolute;
    right: -2px;
    top: 0;
    width: 5px;
    height: 100%;
    cursor: col-resize;
    z-index: 10;
    background: transparent;
}

.column-resize-handle:hover {
    background: rgba(64, 158, 255, 0.5);
}

.column-resize-handle:active {
    background: rgba(64, 158, 255, 0.8);
}

/* Inline cell editing */
.cell-edit-input {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
}

.inline-edit-input {
    width: 100%;
    height: 100%;
    border: 1px solid #409eff;
    background: white;
    padding: 0 4px;
    font-family: inherit;
    font-size: inherit;
    font-weight: inherit;
    font-style: inherit;
    color: inherit;
    outline: none;
    box-sizing: border-box;
}
</style>
