/**
 * Generate a test JRXML file
 * Used to validate whether the JRXML generated by the designer is correct
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// Get the directory of the current file
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Simulate the JRXML content generated by the designer
const testJRXML = `<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports
    http://jasperreports.sourceforge.net/xsd/jasperreport.xsd"
    name="DesignerTestReport"
    pageWidth="595"
    pageHeight="842"
    columnWidth="555"
    leftMargin="20"
    rightMargin="20"
    topMargin="20"
    bottomMargin="20"
    uuid="a1b2c3d4-e5f6-7890-abcd-ef1234567890">

    <field name="productName" class="java.lang.String"/>
    <field name="amount" class="java.math.BigDecimal"/>
    <field name="quantity" class="java.lang.Integer"/>
    <field name="status" class="java.lang.String"/>

    <style name="TitleStyle" mode="Opaque" backcolor="#4472C4" forecolor="#FFFFFF">
        <textElement textAlignment="Center" verticalAlignment="Middle">
            <font fontName="Arial" size="18" isBold="true"/>
        </textElement>
    </style>

    <style name="HeaderStyle" mode="Opaque" backcolor="#D9E2F3" forecolor="#000000">
        <box>
            <pen lineWidth="0.5" lineColor="#000000"/>
        </box>
        <textElement textAlignment="Center" verticalAlignment="Middle">
            <font fontName="Arial" size="12" isBold="true"/>
        </textElement>
    </style>

    <style name="DataStyle" mode="Opaque" backcolor="#FFFFFF" forecolor="#000000">
        <box>
            <pen lineWidth="0.5" lineColor="#000000"/>
        </box>
        <textElement textAlignment="Left" verticalAlignment="Middle">
            <font fontName="Arial" size="11"/>
        </textElement>
    </style>

    <style name="AmountStyle" mode="Opaque" backcolor="#FFFFFF" forecolor="#000000">
        <box>
            <pen lineWidth="0.5" lineColor="#000000"/>
        </box>
        <textElement textAlignment="Right" verticalAlignment="Middle">
            <font fontName="Arial" size="11"/>
        </textElement>
    </style>

    <title>
        <band height="60">
            <staticText style="TitleStyle">
                <reportElement x="0" y="0" width="555" height="60" uuid="12345678-1234-1234-1234-123456789012"/>
                <text><![CDATA[Sales Report Demo]]></text>
            </staticText>
        </band>
    </title>

    <columnHeader>
        <band height="35">
            <staticText style="HeaderStyle">
                <reportElement x="0" y="0" width="200" height="35" uuid="23456789-2345-2345-2345-234567890123"/>
                <text><![CDATA[Product Name]]></text>
            </staticText>
            <staticText style="HeaderStyle">
                <reportElement x="200" y="0" width="100" height="35" uuid="34567890-3456-3456-3456-345678901234"/>
                <text><![CDATA[Quantity]]></text>
            </staticText>
            <staticText style="HeaderStyle">
                <reportElement x="300" y="0" width="120" height="35" uuid="45678901-4567-4567-4567-456789012345"/>
                <text><![CDATA[Unit Price]]></text>
            </staticText>
            <staticText style="HeaderStyle">
                <reportElement x="420" y="0" width="135" height="35" uuid="56789012-5678-5678-5678-567890123456"/>
                <text><![CDATA[Subtotal]]></text>
            </staticText>
        </band>
    </columnHeader>

    <detail>
        <band height="30">
            <textField style="DataStyle">
                <reportElement x="0" y="0" width="200" height="30" uuid="67890123-6789-6789-6789-678901234567"/>
                <textFieldExpression><![CDATA[$F{productName}]]></textFieldExpression>
            </textField>
            <textField style="DataStyle">
                <reportElement x="200" y="0" width="100" height="30" uuid="78901234-7890-7890-7890-789012345678"/>
                <textFieldExpression><![CDATA[$F{quantity}]]></textFieldExpression>
            </textField>
            <textField pattern="#,##0.00" style="AmountStyle">
                <reportElement x="300" y="0" width="120" height="30" uuid="89012345-8901-8901-8901-890123456789"/>
                <textFieldExpression><![CDATA[$F{amount}]]></textFieldExpression>
            </textField>
            <textField pattern="#,##0.00" style="AmountStyle">
                <reportElement x="420" y="0" width="135" height="30" uuid="90123456-9012-9012-9012-901234567890"/>
                <textFieldExpression><![CDATA[$F{amount}.multiply(new java.math.BigDecimal($F{quantity}))]]></textFieldExpression>
            </textField>
        </band>
    </detail>

    <pageFooter>
        <band height="30">
            <frame>
                <reportElement x="0" y="0" width="555" height="30" uuid="a1234567-a123-a123-a123-a12345678901"
                    printWhenExpression="$V{PAGE_NUMBER} > 1"/>
                <textField>
                    <reportElement x="0" y="0" width="555" height="30" uuid="b2345678-b234-b234-b234-b23456789012"/>
                    <textElement textAlignment="Center" verticalAlignment="Middle">
                        <font fontName="Arial" size="10"/>
                    </textElement>
                    <textFieldExpression><![CDATA["Page " + $V{PAGE_NUMBER}]]></textFieldExpression>
                </textField>
            </frame>
        </band>
    </pageFooter>
</jasperReport>`;

// Generate the test file
const outputDir = path.join(__dirname, '..', '..', 'test-reports');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const outputFile = path.join(outputDir, 'designer_test_report.jrxml');
fs.writeFileSync(outputFile, testJRXML, 'utf-8');

console.log(`✓ Test JRXML generated: ${outputFile}`);
console.log('');
console.log('Included components and attributes:');
console.log('  - TextField: pattern, style');
console.log('  - StaticText: style');
console.log('  - Frame: printWhenExpression');
console.log('  - Style: inheritance and definition');
console.log('  - Field: data binding');
